manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: gc9a01a_zephyr_driver
      remote: petejohanson
      revision: main
      clone-depth: 1
